steps:
  # build image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image", "."]
  # push image to container registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-image"]
  # create cluster

  # apply cluster
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --location=asia-southeast2-a
      - --cluster=socket-cluster
      - --image=gcr.io/$PROJECT_ID/my-image:latest
      - --namespace=default

images:
  - "gcr.io/$PROJECT_ID/my-image:latest"
