steps:
  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/socketio"
      - "."
  # Push to GCR
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/socketio"
  # deploy to GKE cluster
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "set"
      - "image"
      - "deployment/socketio"
      - "socketio=gcr.io/$PROJECT_ID/socketio"
      - "--namespace=socketio"
