steps:
  # build image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image:latest", "."]

  # push image to container registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-image:latest"]

  # apply cluster and service
  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      - run
      - --filename=deployment.yaml
      - --location=$_REGION
      - --cluster=$_CLUSTER
      - --image=gcr.io/$PROJECT_ID/my-image:latest
      - --namespace=default

  # apply service configuration
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      - "apply"
      - "-f"
      - "service.yaml"

images:
  - "gcr.io/$PROJECT_ID/my-image"
