steps:
  # Docker build
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--tag=gcr.io/$PROJECT_ID/socketio"
      - "."
  # Push to GCR
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/socketio"

images:
  - "gcr.io/$PROJECT_ID/socketio"
