steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA"]
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "container"
  #     - "clusters"
  #     - "create"
  #     - "my-cluster"
  #     - "--zone"
  #     - "asia-southeast2-a"
  #     - "--num-nodes"
  #     - "1"
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "container"
  #     - "clusters"
  #     - "get-credentials"
  #     - "my-cluster"
  #     - "--zone"
  #     - "asia-southeast2-a"
  # - name: "gcr.io/cloud-builders/gcloud"
  #   args:
  #     - "container"
  #     - "images"
  #     - "add-tag"
  #     - "gcr.io/$PROJECT_ID/my-image"
  #     - "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA"
  # - name: "gcr.io/cloud-builders/kubectl"
  #   args:
  #     - "apply"
  #     - "-f"
  #     - "deployment.yaml"
images:
  - "gcr.io/$PROJECT_ID/my-image:$COMMIT_SHA"
