steps:
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud config set project dcdingproject
        gcloud config set compute/zone asia-southeast2-a
        gcloud config set container/cluster socket-cluster
        kubectl apply -f services.yaml

images:
  - "gcr.io/$PROJECT_ID/my-image:latest"
