apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: gcr.io/dcdingprject/my-image:latest
          ports:
            - containerPort: 80
# service load balancer configuration
# apiVersion: v1
# kind: Service
# metadata:
#   name: my-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: my-app
#   ports:
#     - port: 8090
#       targetPort: 80
#       protocol: TCP
#       name: http
