# service load balancer configuration
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  loadBalancerIP: 34.128.102.82
  selector:
    app: my-app
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
